CREATE DATABASE IF NOT EXISTS brankas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE brankas;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','viewer') NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS akses (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tanggal DATE NOT NULL,
  jam TIME NOT NULL,
  aktivitas VARCHAR(255) NOT NULL,
  foto VARCHAR(255) NOT NULL,
  video VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS settings (
  id TINYINT PRIMARY KEY DEFAULT 1,
  pin_brangkas VARCHAR(20) NOT NULL,
  telegram_bot_token VARCHAR(120) DEFAULT NULL,
  telegram_chat_id VARCHAR(40) DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO settings (id, pin_brangkas) VALUES (1, '1234')
ON DUPLICATE KEY UPDATE pin_brangkas = VALUES(pin_brangkas);
